# Generated by Django 3.0.3 on 2020-02-15 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('default_category_image', models.FileField(blank=True, null=True, upload_to='images/categories/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=128, unique=True)),
                ('coupon_name', models.CharField(db_index=True, max_length=128)),
                ('discount_percentage', models.FloatField()),
                ('expirty_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_requirements', models.CharField(max_length=512)),
                ('company_name', models.CharField(max_length=64)),
                ('contact_name', models.CharField(max_length=64)),
                ('custom_image', models.FileField(blank=True, null=True, upload_to='images/custom_quote/')),
                ('email', models.EmailField(max_length=254)),
                ('fax_no', models.CharField(blank=True, max_length=16, null=True)),
                ('finish_size', models.CharField(max_length=64)),
                ('ink_desc', models.CharField(max_length=64)),
                ('job_type', models.CharField(max_length=32)),
                ('job_desc', models.CharField(max_length=512)),
                ('media_desc', models.CharField(max_length=128)),
                ('old_job_reference', models.CharField(max_length=64)),
                ('phone_no', models.CharField(max_length=16)),
                ('quantity', models.PositiveIntegerField()),
                ('required_ship_date', models.DateTimeField()),
                ('is_proof', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_unit_price', models.FloatField(blank=True, null=True)),
                ('option_name', models.CharField(max_length=64)),
                ('price_unit', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_required_date', models.DateTimeField(blank=True, null=True)),
                ('details', models.CharField(default='', max_length=512)),
                ('order_number', models.CharField(max_length=64, unique=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('At Risk', 'At Risk'), ('Payment Pending', 'Payment Pending'), ('Completed', 'Completed'), ('Delivered', 'Delivered'), ('In Progress', 'In Progress'), ('Yet To Start', 'Yet To Start')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_product_image', models.FileField(blank=True, null=True, upload_to='images/products/')),
                ('one_unit_weight', models.FloatField(default=0)),
                ('weight_unit', models.PositiveIntegerField(default=1)),
                ('product_name', models.CharField(max_length=128)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_coupon_allowed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SubOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Option')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_image', models.FileField(blank=True, null=True, upload_to='images/order_custom/')),
                ('special_note', models.CharField(max_length=128)),
                ('total_price', models.FloatField(default=0)),
                ('total_weight', models.FloatField(default=0)),
                ('product_units', models.FloatField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Product')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Option')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Product'),
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approach_details', models.CharField(max_length=128)),
                ('message', models.CharField(max_length=1024)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Customer')),
            ],
        ),
    ]
