# Generated by Django 3.0.3 on 2020-02-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200216_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='suboption',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
