# Generated by Django 3.0.3 on 2020-02-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_suboption_price'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='coupon',
        #     old_name='expirty_date',
        #     new_name='expiry_date',
        # ),
        # migrations.AddField(
        #     model_name='contactrequest',
        #     name='created_at',
        #     field=models.DateTimeField(auto_now_add=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='contactrequest',
        #     name='updated_at',
        #     field=models.DateTimeField(auto_now=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='option',
        #     name='created_at',
        #     field=models.DateTimeField(auto_now_add=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='option',
        #     name='updated_at',
        #     field=models.DateTimeField(auto_now=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='productoption',
        #     name='created_at',
        #     field=models.DateTimeField(auto_now_add=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='productoption',
        #     name='updated_at',
        #     field=models.DateTimeField(auto_now=True, null=True),
        # ),
    ]
