# Generated by Django 3.0.3 on 2020-03-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200303_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_sub_catgory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='is_suboptions',
            field=models.BooleanField(default=False),
        ),
    ]
