# Generated by Django 3.0.3 on 2020-03-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200305_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_sub_catgory',
            new_name='have_sub_categories',
        ),
    ]
