# Generated by Django 3.0.3 on 2020-03-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200306_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrderOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('Price', models.FloatField(blank=True, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Option')),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.ProductOrder')),
                ('sub_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.SubOption')),
            ],
        ),
    ]
