# Generated by Django 3.0.3 on 2020-03-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200310_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_required_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
