# Generated by Django 3.0.3 on 2020-03-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200312_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorderoption',
            old_name='Price',
            new_name='price',
        ),
    ]
