# Generated by Django 3.0.3 on 2020-03-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200312_0815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOption',
        ),
    ]
