# Generated by Django 3.0.3 on 2020-03-21 11:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200321_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='one_unit_price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.IntegerField(choices=[(1, 'Charge per square foor'), (3, 'Charge with quantity range'), (2, 'Fixed charge for fixed quantity')], default=1),
        ),
    ]
