# Generated by Django 3.0.3 on 2020-03-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_option_option_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suboption',
            old_name='sub_option_name',
            new_name='name',
        ),
    ]
