# Generated by Django 3.0.3 on 2020-03-23 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200323_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorderoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Option'),
        ),
        migrations.AlterField(
            model_name='productorderoption',
            name='product_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_options', to='api.ProductOrder'),
        ),
        migrations.AlterField(
            model_name='productorderoption',
            name='sub_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SubOption'),
        ),
    ]
