# Generated by Django 3.0.3 on 2020-03-26 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200323_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_type',
            field=models.IntegerField(choices=[(5, 'Flat Rate'), (4, 'Basic Percentage'), (7, 'ACCUMULATIVE Percentage'), (6, 'quantity Based')], default=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_type',
            field=models.IntegerField(choices=[(1, 'Charge per square foot'), (3, 'Charge with quantity range'), (2, 'Fixed charge for fixed quantity')], default=1),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_productorders', to='api.Order'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_productorders', to='api.Product'),
        ),
    ]
