# Generated by Django 3.0.3 on 2020-03-26 18:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200326_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
