# Generated by Django 3.0.3 on 2020-03-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200328_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
