# Generated by Django 3.0.3 on 2020-03-29 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_option_option_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('is_suboptions', 'option_name')},
        ),
    ]
