# Generated by Django 3.0.3 on 2020-03-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200329_0627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suboption',
            options={'ordering': ('price', 'name')},
        ),
    ]
