# Generated by Django 3.0.3 on 2020-03-29 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20200329_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suboption',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Option'),
        ),
    ]
