# Generated by Django 3.0.3 on 2020-04-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200329_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customquote',
            name='is_proof',
        ),
        migrations.AddField(
            model_name='customquote',
            name='proof_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='setup_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customquote',
            name='job_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customquote',
            name='job_type',
            field=models.TextField(),
        ),
    ]
