# Generated by Django 3.0.3 on 2020-04-05 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20200404_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_type',
            field=models.IntegerField(choices=[(7, 'Flat Rate'), (6, 'Basic Percentage'), (9, 'ACCUMULATIVE Percentage'), (8, 'quantity Based'), (10, 'multiply value with basic price')], default=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_type',
            field=models.IntegerField(choices=[(1, 'Basic Price calculated per square foot'), (5, 'Basic price calculated with quantity range'), (2, 'Fixed charge for fixed quantity'), (4, 'Basic price based upon two options'), (11, 'Basic price based upon Three options')], default=1),
        ),
        migrations.CreateModel(
            name='TwoDependentSubOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('first_sub_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_first_option_set', to='api.SubOption')),
                ('second_sub_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_second_option_set', to='api.SubOption')),
            ],
        ),
        migrations.CreateModel(
            name='ThreeDependentSubOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('first_sub_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three_first_option_set', to='api.SubOption')),
                ('second_sub_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three_second_option_set', to='api.SubOption')),
                ('third_sub_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three_third_option_set', to='api.SubOption')),
            ],
        ),
    ]
