# Generated by Django 3.0.3 on 2020-04-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20200406_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suboption',
            options={'ordering': ('option', 'price')},
        ),
    ]
