# Generated by Django 3.0.3 on 2020-04-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20200407_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category', 'product_name')},
        ),
    ]
