# Generated by Django 3.0.3 on 2020-04-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20200409_0628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suboption',
            options={'ordering': ('-option', 'price', 'created_at')},
        ),
    ]
