# Generated by Django 3.0.3 on 2020-04-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20200412_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('product', 'is_suboptions', 'created_at')},
        ),
    ]
