# Generated by Django 3.0.3 on 2020-04-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20200412_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suboption',
            options={'ordering': ('price', 'created_at')},
        ),
    ]
