# Generated by Django 3.0.3 on 2020-04-19 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0044_twodependentsuboption_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_code', models.CharField(blank=True, max_length=256, null=True)),
                ('invoice_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('paid_by', models.CharField(blank=True, max_length=512, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=512, null=True)),
                ('sold_to', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='approach_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bussiness_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='fax_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='special_instruction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Mailing Dept.', 'Mailing Dept.'), ('Bindery Dept.', 'Bindery Dept.'), ('On Press', 'On Press'), ('Proof Resubmitted - Waiting approval', 'Proof Resubmitted - Waiting approval'), ('Proof Rejected', 'Proof Rejected'), ('Proof Approved', 'Proof Approved'), ('Proof Submitted', 'Proof Submitted'), ('Prepress Dept.', 'Prepress Dept.'), ('On Hold', 'On Hold'), ('Submitted', 'Submitted'), ('Yet To Start', 'Yet To Start')], max_length=64),
        ),
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('details', models.TextField(max_length=512)),
                ('custom_job_name', models.CharField(blank=True, max_length=256, null=True)),
                ('custom_product_name', models.CharField(blank=True, max_length=256, null=True)),
                ('custom_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_version', models.CharField(blank=True, max_length=16, null=True)),
                ('custom_proof', models.CharField(blank=True, max_length=16, null=True)),
                ('custom_sample', models.TextField()),
                ('custom_paper', models.TextField()),
                ('flat_size', models.CharField(blank=True, max_length=256, null=True)),
                ('ink_color', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField()),
                ('job_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('reference_number', models.CharField(blank=True, max_length=256, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Mailing Dept.', 'Mailing Dept.'), ('Bindery Dept.', 'Bindery Dept.'), ('On Press', 'On Press'), ('Proof Resubmitted - Waiting approval', 'Proof Resubmitted - Waiting approval'), ('Proof Rejected', 'Proof Rejected'), ('Proof Approved', 'Proof Approved'), ('Proof Submitted', 'Proof Submitted'), ('Prepress Dept.', 'Prepress Dept.'), ('On Hold', 'On Hold'), ('Submitted', 'Submitted'), ('Yet To Start', 'Yet To Start')], max_length=64)),
                ('ticket_count', models.PositiveIntegerField(default=0, null=True)),
                ('special_instructoon', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Invoice')),
            ],
        ),
    ]
