# Generated by Django 3.0.3 on 2020-04-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_proofhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='custom_product_name',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='status',
            field=models.CharField(choices=[('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Mailing Dept.', 'Mailing Dept.'), ('Bindery Dept.', 'Bindery Dept.'), ('On Press', 'On Press'), ('Proof Resubmitted - Waiting approval', 'Proof Resubmitted - Waiting approval'), ('Proof Rejected', 'Proof Rejected'), ('Proof Approved', 'Proof Approved'), ('Proof Submitted', 'Proof Submitted'), ('Prepress Dept.', 'Prepress Dept.'), ('On Hold', 'On Hold'), ('Submitted', 'Submitted'), ('Yet To Start', 'Yet To Start')], db_index=True, max_length=64),
        ),
    ]
