# Generated by Django 3.0.3 on 2020-04-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20200421_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='quoted_price',
            field=models.FloatField(null=True),
        ),
    ]
