# Generated by Django 3.0.3 on 2020-04-23 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_customorder_quoted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='custom_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CustomOrder'),
        ),
    ]
