# Generated by Django 3.0.3 on 2020-04-26 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20200423_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('country', models.CharField(blank=True, max_length=16, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=32, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=16, null=True)),
                ('received_by', models.CharField(max_length=32, null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('comments', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('custom_order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CustomOrder')),
            ],
        ),
        migrations.CreateModel(
            name='BoxesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_boxes', models.PositiveIntegerField(default=0)),
                ('quantity_per_box', models.PositiveIntegerField(default=0)),
                ('packing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PackingList')),
            ],
        ),
    ]
