# Generated by Django 3.0.3 on 2020-04-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_boxesdetails_packinglist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='details',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='start_date',
        ),
    ]
