# Generated by Django 3.0.3 on 2020-04-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20200426_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='proof_status',
            field=models.CharField(choices=[('Proof File in Development', 'Proof File in Development'), ('Proof Submitted', 'Proof Submitted'), ('Proof Approved', 'Proof Approved'), ('Proof Rejected', 'Proof Rejected'), ('Awaiting Proof Approval', 'Awaiting Proof Approval'), ('Proof Resubmitted', 'Proof Resubmitted')], default='Proof File in Development', max_length=32),
        ),
    ]
