# Generated by Django 3.0.3 on 2020-04-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_customorder_proof_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proofhistory',
            name='comments',
        ),
        migrations.AddField(
            model_name='proofhistory',
            name='proof_status',
            field=models.CharField(choices=[('Proof File in Development', 'Proof File in Development'), ('Proof Submitted', 'Proof Submitted'), ('Proof Approved', 'Proof Approved'), ('Proof Rejected', 'Proof Rejected'), ('Awaiting Proof Approval', 'Awaiting Proof Approval'), ('Proof Resubmitted', 'Proof Resubmitted')], max_length=256, null=True),
        ),
    ]
