# Generated by Django 3.0.3 on 2020-04-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20200427_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofhistory',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
