# Generated by Django 3.0.3 on 2020-04-28 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20200427_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer'),
        ),
    ]
