# Generated by Django 3.0.3 on 2020-05-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20200502_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='second_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='third_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
