# Generated by Django 3.0.3 on 2020-05-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20200503_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinglist',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
