# Generated by Django 3.0.3 on 2020-05-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20200503_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxesdetails',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='total_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
