# Generated by Django 3.0.3 on 2020-05-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20200503_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='resale_no',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'In active')], default=1),
        ),
    ]
