# Generated by Django 3.0.3 on 2020-05-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20200506_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='status',
            field=models.CharField(choices=[('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Mailing Dept.', 'Mailing Dept.'), ('Bindery Dept.', 'Bindery Dept.'), ('On Press', 'On Press'), ('Proof Resubmitted - Waiting approval', 'Proof Resubmitted - Waiting approval'), ('Proof Rejected', 'Proof Rejected'), ('Proof Approved', 'Proof Approved'), ('Proof Submitted', 'Proof Submitted'), ('Prepress Dept.', 'Prepress Dept.'), ('On Hold', 'On Hold'), ('Submitted', 'Submitted')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Mailing Dept.', 'Mailing Dept.'), ('Bindery Dept.', 'Bindery Dept.'), ('On Press', 'On Press'), ('Proof Resubmitted - Waiting approval', 'Proof Resubmitted - Waiting approval'), ('Proof Rejected', 'Proof Rejected'), ('Proof Approved', 'Proof Approved'), ('Proof Submitted', 'Proof Submitted'), ('Prepress Dept.', 'Prepress Dept.'), ('On Hold', 'On Hold'), ('Submitted', 'Submitted')], max_length=64),
        ),
    ]
