# Generated by Django 3.0.3 on 2020-05-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20200507_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
