# Generated by Django 3.0.3 on 2020-05-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_delete_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
