# Generated by Django 3.0.3 on 2020-05-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_customorder_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='shipping_contact_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='shipping_street_address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='shipping_type',
            field=models.CharField(blank=True, choices=[('No Shipment', 'No Shipment'), ('Delivery', 'Delivery'), ('Shipping', 'Shipping')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='shipping_zip_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
