# Generated by Django 3.0.3 on 2020-05-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_boxesdetails_job_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='custom_sample',
        ),
    ]
