# Generated by Django 3.0.3 on 2020-05-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_boxesdetails_job_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productorderoption',
            name='option',
        ),
        migrations.RemoveField(
            model_name='productorderoption',
            name='product_order',
        ),
        migrations.RemoveField(
            model_name='productorderoption',
            name='sub_option',
        ),
        migrations.AlterField(
            model_name='customorder',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='special_instructoon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
        migrations.DeleteModel(
            name='ProductOrderOption',
        ),
    ]
