# Generated by Django 3.0.3 on 2020-05-16 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20200516_0324'),
        ('api', '0070_remove_customorder_custom_sample'),
    ]

    operations = [
    ]
