# Generated by Django 3.0.3 on 2020-05-16 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0070_auto_20200516_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_note', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=256, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/cart-images/')),
                ('proof_status', models.CharField(choices=[('Proof File in Development', 'Proof File in Development'), ('Proof Submitted', 'Proof Submitted'), ('Proof Approved', 'Proof Approved'), ('Proof Rejected', 'Proof Rejected'), ('Awaiting Proof Approval', 'Awaiting Proof Approval'), ('Proof Resubmitted', 'Proof Resubmitted')], default='Proof File in Development', max_length=32)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Mailing Dept.', 'Mailing Dept.'), ('Bindery Dept.', 'Bindery Dept.'), ('On Press', 'On Press'), ('Proof Resubmitted - Waiting approval', 'Proof Resubmitted - Waiting approval'), ('Proof Rejected', 'Proof Rejected'), ('Proof Approved', 'Proof Approved'), ('Proof Submitted', 'Proof Submitted'), ('Prepress Dept.', 'Prepress Dept.'), ('On Hold', 'On Hold'), ('Submitted', 'Submitted')], db_index=True, max_length=64)),
                ('quoted_price', models.FloatField(null=True)),
                ('shipping_type', models.CharField(blank=True, choices=[('No Shipment', 'No Shipment'), ('Delivery', 'Delivery'), ('Shipping', 'Shipping')], max_length=64, null=True)),
                ('is_cart', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Option')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_options', to='cart.Order')),
                ('sub_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SubOption')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerShippingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_contact_name', models.CharField(blank=True, max_length=256, null=True)),
                ('shipping_street_address', models.CharField(blank=True, max_length=512, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=64, null=True)),
                ('shipping_state', models.CharField(blank=True, max_length=64, null=True)),
                ('shipping_zip_code', models.CharField(blank=True, max_length=16, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
            ],
        ),
    ]
