# Generated by Django 3.0.3 on 2020-02-14 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=64)),
                ('is_deleted', models.BooleanField(default=False)),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apis.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(db_index=True, max_length=128)),
                ('coupon_code', models.CharField(max_length=128, unique=True)),
                ('discount_percentage', models.FloatField()),
                ('last_active_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=64)),
                ('price_unit', models.PositiveIntegerField(default=1)),
                ('one_unit_price', models.FloatField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(default='', max_length=512)),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('At Risk', 'At Risk'), ('Payment Pending', 'Payment Pending'), ('Completed', 'Completed'), ('Delivered', 'Delivered'), ('In Progress', 'In Progress'), ('Yet To Start', 'Yet To Start')], max_length=32)),
                ('customer_required_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apis.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('weight_unit', models.PositiveIntegerField(default=1)),
                ('one_unit_weight', models.FloatField(default=0)),
                ('is_coupon_allowed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apis.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SubOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(max_length=64)),
                ('is_deleted', models.BooleanField(default=False)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apis.Option')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_note', models.CharField(max_length=128)),
                ('total_price', models.FloatField(default=0)),
                ('total_weight', models.FloatField(default=0)),
                ('product_units', models.FloatField(default=1)),
                ('custom_image', models.FileField(upload_to='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apis.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apis.Product')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apis.Product'),
        ),
    ]
