# Generated by Django 3.0.3 on 2020-02-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
