# Generated by Django 3.0.3 on 2020-02-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20200214_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='default_image',
            field=models.FileField(blank=True, null=True, upload_to='categoryimages/'),
        ),
    ]
