# Generated by Django 3.0.3 on 2020-02-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20200214_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='default_image',
            new_name='default_category_image',
        ),
        migrations.AddField(
            model_name='product',
            name='default_product_image',
            field=models.FileField(blank=True, null=True, upload_to='categoryimages/'),
        ),
    ]
